main = ".open-next/worker.ts"
name = "openint-production-govsignals"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

# wrangler.toml
[observability.logs]
enabled = true


[alias]
"#crypto" = "./worker-aliases/crypto"
"critters" = "./worker-aliases/critters"
"depd" = "./worker-aliases/depd"

[vars]
# Created by Vercel CLI
CLERK_SECRET_KEY="sk_live_ePRewT0BRbyM38jLNxoVpaVkMa1QFFQwpvO8A3aGgh"
DATABASE_URL="postgresql://neondb_owner:TlYLnid3oV2Q@ep-green-paper-a6n4ub86-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require"
DATABASE_URL_UNPOOLED="postgresql://neondb_owner:TlYLnid3oV2Q@ep-green-paper-a6n4ub86.us-west-2.aws.neon.tech/neondb?sslmode=require"
INNGEST_EVENT_KEY="CWUKqKuVOhoYphf7eV2F206XlupESBcpjUPQ8IfT-DmIHokTBEGXw5l99GUA9OTJHHVDE1132Mz4C-6CuleR-Q"
INNGEST_SIGNING_KEY="signkey-prod-f413b81200cb523cad27528e46f7a4f26e10802adb1587b5eb3e4ce9603f8bab"
INTEGRATION_TEST_SECRET="eix3waphiekuyuu4raiPhe4zem4Wai2o"
JWT_SECRET="QlZq8/04M/WUeG6UAVeP88FHqCNKbYr9trI1v/xCJgxSXkUVc/G3MaXeuAKOYDi7bG+/aFqOqNOo48ojeN3Wyg=="
NANGO_SECRET_KEY="3e36981c-cf37-4d15-be88-5faa72716065"
NEXT_PUBLIC_API_URL="https://api.openint.dev/v0"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_live_Y2xlcmsub3BlbmludC5kZXYk"
NEXT_PUBLIC_COMMANDBAR_ORG_ID="6df4d085"
NEXT_PUBLIC_NANGO_PUBLIC_KEY="c0c42833-3cb9-4bf7-853c-cd3016c3c9b7"
NEXT_PUBLIC_POSTHOG_WRITEKEY="phc_GyCVUD9M74GA9ZJpMQYlojZV0Nb6rbMBDHhWFJ77e7I"
NEXT_PUBLIC_SENTRY_DSN="https://06079aad114dfd381ce53ee5b6207e5a@o4508568568266752.ingest.de.sentry.io/4508568576065616"
NEXT_PUBLIC_SENTRY_ORG="openint"
NEXT_PUBLIC_SERVER_URL="https://local.openint.dev"
NX_DAEMON="false"
POSTGRES_URL="postgresql://postgres.qhzoloqfqrscamxcaiyo:YZltu9mnZ2covACF@aws-0-us-west-1.pooler.supabase.com:6543/postgres"
SENTRY_AUTH_TOKEN="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"
SENTRY_CRON_MONITOR_URL="https://o4508568568266752.ingest.de.sentry.io/api/4508568576065616/cron/prod-schedule-syncs/06079aad114dfd381ce53ee5b6207e5a/"
SENTRY_IGNORE_API_RESOLUTION_ERROR="true"
SENTRY_ORG="openint"
TURBO_CACHE="remote:rw"
TURBO_DOWNLOAD_LOCAL_ENABLED="true"
TURBO_REMOTE_ONLY="true"
TURBO_RUN_SUMMARY="true"
VERCEL="1"
VERCEL_ENV="production"
VERCEL_GIT_COMMIT_AUTHOR_LOGIN=""
VERCEL_GIT_COMMIT_AUTHOR_NAME=""
VERCEL_GIT_COMMIT_MESSAGE=""
VERCEL_GIT_COMMIT_REF=""
VERCEL_GIT_COMMIT_SHA=""
VERCEL_GIT_PREVIOUS_SHA=""
VERCEL_GIT_PROVIDER=""
VERCEL_GIT_PULL_REQUEST_ID=""
VERCEL_GIT_REPO_ID=""
VERCEL_GIT_REPO_OWNER=""
VERCEL_GIT_REPO_SLUG=""
VERCEL_TARGET_ENV="production"
VERCEL_URL=""
ccfg_hubspot_CLIENT_ID="52d5fd36-11c7-4507-968a-a40f9fd05375"
ccfg_hubspot_CLIENT_SECRET="6af1909c-b552-4162-a36b-076e2a0af1d7"
ccfg_hubspot__SCOPE="oauth,crm.objects.companies.read,crm.objects.contacts.read,crm.objects.custom.read,crm.objects.deals.read,crm.objects.deals.write,crm.objects.owners.read,crm.schemas.custom.read,crm.schemas.custom.write,crm.schemas.deals.read,sales-email-read"
ccfg_plaid__CLIENT_ID="5bba45cdf17fb3001118de15"
ccfg_plaid__CLIENT_SECRET_PRODUCTION="8a757d2ba17b7d34eaa819ef28dc5c"
ccfg_plaid__CLIENT_SECRET_SANDBOX="b8ce2bdf52a78a1fed582acd6081bf"
ccfg_qbo_CLIENT_ID="ABSSMHdQMwtgyabxBYI4Du0h6d15YgXZ0TCcM4E4dng2kxpIUW"
ccfg_qbo_CLIENT_SECRET="jIMCbkpOjORlTSeshqzLRl5uRguwrWB2ryM1OJau"
ccfg_qbo_SCOPE="com.intuit.quickbooks.accounting"
conn_greenhouse_API_KEY="e5a6a86e28e17bd5d17307e6fcbb3683-8"
int_debug=""
int_discord__CLIENT_ID="1174073705513619498"
int_discord__CLIENT_SECRET="RaJyBVvnj3kj-3SYFTYKl24FgCmA6Ix2"
int_heron__apiKey="key_02baf42dcb372814cc9940c3543e02815b353439d0fd5382"
int_hubspot__CLIENT_ID_OLD="cf1c8463-7285-4cd7-b44f-3f750d375c75"
int_hubspot__CLIENT_SECRET_OLD="fca3418d-139c-4b95-a4ff-4e4e102c5857"
int_merge__apiKey="9PnbT8WLGraT5Y4YtNkWIdc5fR4oNCM3SnMlW_nWQF1TkDCO9ia5-A"
int_plaid__CLIENT_ID="5bba45cdf17fb3001118de15"
int_plaid__CLIENT_SECRET_DEVELOPMENT="TODO: Properly disable this as we are limited to 100 development accounts. (Real value is 2055b28588943cbde1973533c93892)"
int_plaid__CLIENT_SECRET_PRODUCTION="8a757d2ba17b7d34eaa819ef28dc5c"
int_plaid__CLIENT_SECRET_SANDBOX="b8ce2bdf52a78a1fed582acd6081bf"

NEXT_PUBLIC_RUNTIME_ENV="edge"