# NOTE: Postgres (and certainly supabase) is not a requirement for usage in OpenInt, though it is the default set
# Therefore this docker-compose file is entirely optional
version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    # command: postgres -c log_statement=all
    restart: always
    environment:
      POSTGRES_DB: postgres # Only database named `postgres` works with pg_cron by default
      POSTGRES_PASSWORD: password
    command: ["postgres", "-c", "log_statement=all", "-c", "max_connections=500"]

  supabase:
    image: supabase/postgres:15.8.1.017 # For some reason "lastest tag" is having issues... so we pin to a specific version latest as of 2024-12-20_0055
    ports:
      - 5433:5432 # Change the port to avoid conflict with the default postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c log_statement=all -c max_connections=500
    restart: always
    environment:
      POSTGRES_DB: supabase # Only database named `postgres` works with pg_cron by default
      POSTGRES_PASSWORD: password

  inngest:
      image: inngest/inngest
      command: 'inngest dev'
      ports:
        - '8288:8288'
