# NOTE: Postgres (and certainly supabase) is not a requirement for usage in OpenInt, though it is the default set
# Therefore this docker-compose file is entirely optional
version: '3'
services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    # command: postgres -c log_statement=all
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres # Only database named `postgres` works with pg_cron by default
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    command: '-d 1'
    volumes:
      - db_data:/var/lib/postgresql/data

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      ## Ensure that this matches the .env.dev DATABASE_URL
      - PG_CONNECTION_STRING=postgres://postgres:password@postgres:5432/postgres
    ports:
      - '4444:4444'
    depends_on:
      postgres:
        condition: service_healthy

  inngest:
    image: inngest/inngest
    command: 'inngest dev'
    ports:
      - '8288:8288'

volumes:
  db_data:
