import {
  def as connectorGoogledrive_def,
  server as connectorGoogledrive_server,
} from './googledrive/def'

// generated by _generateConnectorLists.ts. Do not modify by hand
export type {JsonConnectorDef as ConnectorDef} from './def'
export type {AuthType} from './def'

export {connectorGoogledrive_server, connectorGoogledrive_def}
