import {server as connectorAircall_server} from './aircall'
import {def as connectorAircall_def} from './aircall/def'
import {server as connectorConfluence_server} from './confluence'
import {def as connectorConfluence_def} from './confluence/def'
import {server as connectorGooglecalendar_server} from './googlecalendar'
import {def as connectorGooglecalendar_def} from './googlecalendar/def'
import {server as connectorGoogledocs_server} from './googledocs'
import {def as connectorGoogledocs_def} from './googledocs/def'
import {server as connectorGoogledrive_server} from './googledrive'
import {def as connectorGoogledrive_def} from './googledrive/def'
import {server as connectorGooglemail_server} from './googlemail'
import {def as connectorGooglemail_def} from './googlemail/def'
import {server as connectorGooglesheet_server} from './googlesheet'
import {def as connectorGooglesheet_def} from './googlesheet/def'

// generated by _generateConnectorLists.ts. Do not modify by hand
export type {JsonConnectorDef} from './def'
export type {AuthType} from './def'

export {
  connectorAircall_server,
  connectorAircall_def,
  connectorConfluence_server,
  connectorConfluence_def,
  connectorGooglecalendar_server,
  connectorGooglecalendar_def,
  connectorGoogledocs_server,
  connectorGoogledocs_def,
  connectorGoogledrive_server,
  connectorGoogledrive_def,
  connectorGooglemail_server,
  connectorGooglemail_def,
  connectorGooglesheet_server,
  connectorGooglesheet_def,
}
