// generated by _generateConnectorLists.ts. Do not modify by hand

import type {Meta, StoryObj} from '@storybook/react'
import {defConnectors} from '@openint/all-connectors/connectors.def'
import {zodToOas31Schema} from '@openint/util/schema'
import {JSONSchemaForm} from '../components/schema-form/JSONSchemaForm'

const meta: Meta<typeof JSONSchemaForm> = {
  component: JSONSchemaForm,
  parameters: {layout: 'centered'},
  decorators: [
    (Story) => (
      <div className="max-w-lg">
        <Story />
      </div>
    ),
  ],
}

export default meta
type Story = StoryObj<typeof meta>

export const aircallConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['aircall'].schemas.connectorConfig,
    ),
  },
}

export const aircallConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['aircall'].schemas.connectionSettings,
    ),
  },
}

export const airtableConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['airtable'].schemas.connectionSettings,
    ),
  },
}

export const apolloConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['apollo'].schemas.connectionSettings,
    ),
  },
}

export const brexConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(defConnectors['brex'].schemas.connectorConfig),
  },
}

export const brexConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['brex'].schemas.connectionSettings,
    ),
  },
}

export const codaConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['coda'].schemas.connectionSettings,
    ),
  },
}

export const confluenceConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['confluence'].schemas.connectorConfig,
    ),
  },
}

export const confluenceConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['confluence'].schemas.connectionSettings,
    ),
  },
}

export const discordConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['discord'].schemas.connectorConfig,
    ),
  },
}

export const discordConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['discord'].schemas.connectionSettings,
    ),
  },
}

export const facebookConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['facebook'].schemas.connectorConfig,
    ),
  },
}

export const facebookConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['facebook'].schemas.connectionSettings,
    ),
  },
}

export const finchConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['finch'].schemas.connectorConfig,
    ),
  },
}

export const finchConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['finch'].schemas.connectionSettings,
    ),
  },
}

export const firebaseConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['firebase'].schemas.connectionSettings,
    ),
  },
}

export const foreceiptConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['foreceipt'].schemas.connectionSettings,
    ),
  },
}

export const githubConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['github'].schemas.connectorConfig,
    ),
  },
}

export const githubConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['github'].schemas.connectionSettings,
    ),
  },
}

export const gongConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(defConnectors['gong'].schemas.connectorConfig),
  },
}

export const gongConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['gong'].schemas.connectionSettings,
    ),
  },
}

export const googlecalendarConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googlecalendar'].schemas.connectorConfig,
    ),
  },
}

export const googlecalendarConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googlecalendar'].schemas.connectionSettings,
    ),
  },
}

export const googledocsConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googledocs'].schemas.connectorConfig,
    ),
  },
}

export const googledocsConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googledocs'].schemas.connectionSettings,
    ),
  },
}

export const googledriveConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googledrive'].schemas.connectorConfig,
    ),
  },
}

export const googledriveConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googledrive'].schemas.connectionSettings,
    ),
  },
}

export const googlemailConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googlemail'].schemas.connectorConfig,
    ),
  },
}

export const googlemailConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googlemail'].schemas.connectionSettings,
    ),
  },
}

export const googlesheetConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googlesheet'].schemas.connectorConfig,
    ),
  },
}

export const googlesheetConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['googlesheet'].schemas.connectionSettings,
    ),
  },
}

export const greenhouseConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['greenhouse'].schemas.connectionSettings,
    ),
  },
}

export const heronConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['heron'].schemas.connectorConfig,
    ),
  },
}

export const hubspotConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['hubspot'].schemas.connectorConfig,
    ),
  },
}

export const hubspotConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['hubspot'].schemas.connectionSettings,
    ),
  },
}

export const instagramConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['instagram'].schemas.connectorConfig,
    ),
  },
}

export const instagramConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['instagram'].schemas.connectionSettings,
    ),
  },
}

export const intercomConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['intercom'].schemas.connectorConfig,
    ),
  },
}

export const intercomConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['intercom'].schemas.connectionSettings,
    ),
  },
}

export const jiraConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(defConnectors['jira'].schemas.connectorConfig),
  },
}

export const jiraConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['jira'].schemas.connectionSettings,
    ),
  },
}

export const kustomerConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['kustomer'].schemas.connectorConfig,
    ),
  },
}

export const kustomerConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['kustomer'].schemas.connectionSettings,
    ),
  },
}

export const leverConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['lever'].schemas.connectorConfig,
    ),
  },
}

export const leverConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['lever'].schemas.connectionSettings,
    ),
  },
}

export const linearConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['linear'].schemas.connectorConfig,
    ),
  },
}

export const linearConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['linear'].schemas.connectionSettings,
    ),
  },
}

export const linkedinConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['linkedin'].schemas.connectorConfig,
    ),
  },
}

export const linkedinConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['linkedin'].schemas.connectionSettings,
    ),
  },
}

export const lunchmoneyConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['lunchmoney'].schemas.connectorConfig,
    ),
  },
}

export const mercuryConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['mercury'].schemas.connectorConfig,
    ),
  },
}

export const mergeConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['merge'].schemas.connectorConfig,
    ),
  },
}

export const mergeConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['merge'].schemas.connectionSettings,
    ),
  },
}

export const microsoftConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['microsoft'].schemas.connectorConfig,
    ),
  },
}

export const microsoftConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['microsoft'].schemas.connectionSettings,
    ),
  },
}

export const mootaConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['moota'].schemas.connectorConfig,
    ),
  },
}

export const notionConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['notion'].schemas.connectorConfig,
    ),
  },
}

export const notionConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['notion'].schemas.connectionSettings,
    ),
  },
}

export const onebrickConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['onebrick'].schemas.connectorConfig,
    ),
  },
}

export const onebrickConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['onebrick'].schemas.connectionSettings,
    ),
  },
}

export const outreachConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['outreach'].schemas.connectorConfig,
    ),
  },
}

export const outreachConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['outreach'].schemas.connectionSettings,
    ),
  },
}

export const pipedriveConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['pipedrive'].schemas.connectorConfig,
    ),
  },
}

export const pipedriveConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['pipedrive'].schemas.connectionSettings,
    ),
  },
}

export const plaidConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['plaid'].schemas.connectorConfig,
    ),
  },
}

export const plaidConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['plaid'].schemas.connectionSettings,
    ),
  },
}

export const postgresConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['postgres'].schemas.connectionSettings,
    ),
  },
}

export const quickbooksConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['quickbooks'].schemas.connectorConfig,
    ),
  },
}

export const quickbooksConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['quickbooks'].schemas.connectionSettings,
    ),
  },
}

export const rampConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(defConnectors['ramp'].schemas.connectorConfig),
  },
}

export const rampConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['ramp'].schemas.connectionSettings,
    ),
  },
}

export const redditConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['reddit'].schemas.connectorConfig,
    ),
  },
}

export const redditConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['reddit'].schemas.connectionSettings,
    ),
  },
}

export const salesforceConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['salesforce'].schemas.connectorConfig,
    ),
  },
}

export const salesforceConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['salesforce'].schemas.connectionSettings,
    ),
  },
}

export const salesloftConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['salesloft'].schemas.connectorConfig,
    ),
  },
}

export const salesloftConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['salesloft'].schemas.connectionSettings,
    ),
  },
}

export const saltedgeConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['saltedge'].schemas.connectorConfig,
    ),
  },
}

export const saltedgeConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['saltedge'].schemas.connectionSettings,
    ),
  },
}

export const sharepointonlineConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['sharepointonline'].schemas.connectorConfig,
    ),
  },
}

export const sharepointonlineConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['sharepointonline'].schemas.connectionSettings,
    ),
  },
}

export const slackConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['slack'].schemas.connectorConfig,
    ),
  },
}

export const slackConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['slack'].schemas.connectionSettings,
    ),
  },
}

export const splitwiseConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['splitwise'].schemas.connectionSettings,
    ),
  },
}

export const stripeConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['stripe'].schemas.connectorConfig,
    ),
  },
}

export const stripeConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['stripe'].schemas.connectionSettings,
    ),
  },
}

export const tellerConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['teller'].schemas.connectorConfig,
    ),
  },
}

export const tellerConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['teller'].schemas.connectionSettings,
    ),
  },
}

export const togglConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['toggl'].schemas.connectionSettings,
    ),
  },
}

export const twentyConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['twenty'].schemas.connectionSettings,
    ),
  },
}

export const twitterConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['twitter'].schemas.connectorConfig,
    ),
  },
}

export const twitterConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['twitter'].schemas.connectionSettings,
    ),
  },
}

export const venmoConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['venmo'].schemas.connectorConfig,
    ),
  },
}

export const venmoConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['venmo'].schemas.connectionSettings,
    ),
  },
}

export const wiseConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['wise'].schemas.connectionSettings,
    ),
  },
}

export const xeroConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(defConnectors['xero'].schemas.connectorConfig),
  },
}

export const xeroConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['xero'].schemas.connectionSettings,
    ),
  },
}

export const yodleeConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['yodlee'].schemas.connectorConfig,
    ),
  },
}

export const yodleeConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['yodlee'].schemas.connectionSettings,
    ),
  },
}

export const zohodeskConnectorConfig: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['zohodesk'].schemas.connectorConfig,
    ),
  },
}

export const zohodeskConnectionSettings: Story = {
  args: {
    jsonSchema: zodToOas31Schema(
      defConnectors['zohodesk'].schemas.connectionSettings,
    ),
  },
}
