// generated file. Do not modify by hand

// Generated by generateConnectorStories.ts
import type {Meta, StoryObj} from '@storybook/react'
import type {ConnectorName} from '@openint/all-connectors/name'

import {defConnectors} from '@openint/all-connectors/connectors.def'
import {getConnectorModel} from '@openint/api-v1/models'
import {ConnectorDisplay} from '../domain-components/ConnectorDisplay'

function StoryWrapper(props: {name: ConnectorName}) {
  const def = defConnectors[props.name]
  if (!def) {
    throw new Error('Connector ' + props.name + ' not found')
  }
  const connector = getConnectorModel(def, {
    includeSchemas: true,
  })

  return <ConnectorDisplay connector={connector} />
}

const meta: Meta<typeof StoryWrapper> = {
  title: 'All Connectors/connector',
  component: StoryWrapper,
  parameters: {layout: 'centered'},
  tags: ['autodocs'],
}

export default meta
type Story = StoryObj<typeof meta>

export const acmeOauth2ConnectorDisplay: Story = {
  args: {name: 'acme-oauth2'},
}

export const aircallConnectorDisplay: Story = {
  args: {name: 'aircall'},
}

export const confluenceConnectorDisplay: Story = {
  args: {name: 'confluence'},
}

export const discordConnectorDisplay: Story = {
  args: {name: 'discord'},
}

export const facebookConnectorDisplay: Story = {
  args: {name: 'facebook'},
}

export const githubConnectorDisplay: Story = {
  args: {name: 'github'},
}

export const gongConnectorDisplay: Story = {
  args: {name: 'gong'},
}

export const googleCalendarConnectorDisplay: Story = {
  args: {name: 'google-calendar'},
}

export const googleDocsConnectorDisplay: Story = {
  args: {name: 'google-docs'},
}

export const googleDriveConnectorDisplay: Story = {
  args: {name: 'google-drive'},
}

export const googleMailConnectorDisplay: Story = {
  args: {name: 'google-mail'},
}

export const googleSheetConnectorDisplay: Story = {
  args: {name: 'google-sheet'},
}

export const hubspotConnectorDisplay: Story = {
  args: {name: 'hubspot'},
}

export const instagramConnectorDisplay: Story = {
  args: {name: 'instagram'},
}

export const intercomConnectorDisplay: Story = {
  args: {name: 'intercom'},
}

export const jiraConnectorDisplay: Story = {
  args: {name: 'jira'},
}

export const leverConnectorDisplay: Story = {
  args: {name: 'lever'},
}

export const linearConnectorDisplay: Story = {
  args: {name: 'linear'},
}

export const linkedinConnectorDisplay: Story = {
  args: {name: 'linkedin'},
}

export const notionConnectorDisplay: Story = {
  args: {name: 'notion'},
}

export const outreachConnectorDisplay: Story = {
  args: {name: 'outreach'},
}

export const pipedriveConnectorDisplay: Story = {
  args: {name: 'pipedrive'},
}

export const quickbooksConnectorDisplay: Story = {
  args: {name: 'quickbooks'},
}

export const redditConnectorDisplay: Story = {
  args: {name: 'reddit'},
}

export const salesloftConnectorDisplay: Story = {
  args: {name: 'salesloft'},
}

export const sharepointConnectorDisplay: Story = {
  args: {name: 'sharepoint'},
}

export const slackConnectorDisplay: Story = {
  args: {name: 'slack'},
}

export const twitterConnectorDisplay: Story = {
  args: {name: 'twitter'},
}

export const xeroConnectorDisplay: Story = {
  args: {name: 'xero'},
}

export const zohoDeskConnectorDisplay: Story = {
  args: {name: 'zoho-desk'},
}

export const airtableConnectorDisplay: Story = {
  args: {name: 'airtable'},
}

export const apolloConnectorDisplay: Story = {
  args: {name: 'apollo'},
}

export const brexConnectorDisplay: Story = {
  args: {name: 'brex'},
}

export const codaConnectorDisplay: Story = {
  args: {name: 'coda'},
}

export const finchConnectorDisplay: Story = {
  args: {name: 'finch'},
}

export const firebaseConnectorDisplay: Story = {
  args: {name: 'firebase'},
}

export const foreceiptConnectorDisplay: Story = {
  args: {name: 'foreceipt'},
}

export const greenhouseConnectorDisplay: Story = {
  args: {name: 'greenhouse'},
}

export const heronConnectorDisplay: Story = {
  args: {name: 'heron'},
}

export const lunchmoneyConnectorDisplay: Story = {
  args: {name: 'lunchmoney'},
}

export const mercuryConnectorDisplay: Story = {
  args: {name: 'mercury'},
}

export const mergeConnectorDisplay: Story = {
  args: {name: 'merge'},
}

export const mootaConnectorDisplay: Story = {
  args: {name: 'moota'},
}

export const onebrickConnectorDisplay: Story = {
  args: {name: 'onebrick'},
}

export const plaidConnectorDisplay: Story = {
  args: {name: 'plaid'},
}

export const postgresConnectorDisplay: Story = {
  args: {name: 'postgres'},
}

export const rampConnectorDisplay: Story = {
  args: {name: 'ramp'},
}

export const saltedgeConnectorDisplay: Story = {
  args: {name: 'saltedge'},
}

export const splitwiseConnectorDisplay: Story = {
  args: {name: 'splitwise'},
}

export const stripeConnectorDisplay: Story = {
  args: {name: 'stripe'},
}

export const tellerConnectorDisplay: Story = {
  args: {name: 'teller'},
}

export const togglConnectorDisplay: Story = {
  args: {name: 'toggl'},
}

export const twentyConnectorDisplay: Story = {
  args: {name: 'twenty'},
}

export const venmoConnectorDisplay: Story = {
  args: {name: 'venmo'},
}

export const wiseConnectorDisplay: Story = {
  args: {name: 'wise'},
}

export const yodleeConnectorDisplay: Story = {
  args: {name: 'yodlee'},
}
