// generated file. Do not modify by hand

// Generated by generateConnectorStories.ts
import type {ConnectorName} from '@openint/all-connectors/name'
import type {Meta, StoryObj} from '@storybook/react'
import {defConnectors} from '@openint/all-connectors/connectors.def'
import {Card} from '@openint/shadcn/ui'
import {zodToOas31Schema} from '@openint/util/schema'
import {JSONSchemaForm} from '../components/schema-form/JSONSchemaForm'

function FormWrapper(props: {name: ConnectorName}) {
  const schemas = defConnectors[props.name].schemas
  if (!('connector_config' in schemas)) {
    throw new Error(
      'Connector ' + props.name + ' does not have a connector_config',
    )
  }

  return (
    <Card className="w-md p-4">
      <h1 className="text-lg font-bold">{props.name} connector_config</h1>
      <hr />
      <JSONSchemaForm
        debugMode
        jsonSchema={zodToOas31Schema(schemas.connector_config)}
      />
    </Card>
  )
}

const meta: Meta<typeof FormWrapper> = {
  title: 'All Connectors/connector_config',
  component: FormWrapper,
  parameters: {layout: 'centered'},
}

export default meta
type Story = StoryObj<typeof meta>

export const acmeOauth2ConnectorConfig: Story = {
  args: {name: 'acme-oauth2'},
}

export const sharepointonlineConnectorConfig: Story = {
  args: {name: 'sharepointonline'},
}

export const slackConnectorConfig: Story = {
  args: {name: 'slack'},
}

export const githubConnectorConfig: Story = {
  args: {name: 'github'},
}

export const quickbooksConnectorConfig: Story = {
  args: {name: 'quickbooks'},
}

export const googlemailConnectorConfig: Story = {
  args: {name: 'googlemail'},
}

export const notionConnectorConfig: Story = {
  args: {name: 'notion'},
}

export const linkedinConnectorConfig: Story = {
  args: {name: 'linkedin'},
}

export const googledocsConnectorConfig: Story = {
  args: {name: 'googledocs'},
}

export const aircallConnectorConfig: Story = {
  args: {name: 'aircall'},
}

export const googlecalendarConnectorConfig: Story = {
  args: {name: 'googlecalendar'},
}

export const googlesheetConnectorConfig: Story = {
  args: {name: 'googlesheet'},
}

export const discordConnectorConfig: Story = {
  args: {name: 'discord'},
}

export const hubspotConnectorConfig: Story = {
  args: {name: 'hubspot'},
}

export const salesforceConnectorConfig: Story = {
  args: {name: 'salesforce'},
}

export const linearConnectorConfig: Story = {
  args: {name: 'linear'},
}

export const confluenceConnectorConfig: Story = {
  args: {name: 'confluence'},
}

export const googledriveConnectorConfig: Story = {
  args: {name: 'googledrive'},
}

export const brexConnectorConfig: Story = {
  args: {name: 'brex'},
}

export const finchConnectorConfig: Story = {
  args: {name: 'finch'},
}

export const heronConnectorConfig: Story = {
  args: {name: 'heron'},
}

export const lunchmoneyConnectorConfig: Story = {
  args: {name: 'lunchmoney'},
}

export const mercuryConnectorConfig: Story = {
  args: {name: 'mercury'},
}

export const mergeConnectorConfig: Story = {
  args: {name: 'merge'},
}

export const mootaConnectorConfig: Story = {
  args: {name: 'moota'},
}

export const onebrickConnectorConfig: Story = {
  args: {name: 'onebrick'},
}

export const plaidConnectorConfig: Story = {
  args: {name: 'plaid'},
}

export const rampConnectorConfig: Story = {
  args: {name: 'ramp'},
}

export const saltedgeConnectorConfig: Story = {
  args: {name: 'saltedge'},
}

export const stripeConnectorConfig: Story = {
  args: {name: 'stripe'},
}

export const tellerConnectorConfig: Story = {
  args: {name: 'teller'},
}

export const venmoConnectorConfig: Story = {
  args: {name: 'venmo'},
}

export const yodleeConnectorConfig: Story = {
  args: {name: 'yodlee'},
}
