import path from 'node:path'

import {camelCase} from '@openint/util/string-utils'
import {defConnectors} from '../connectors.def'
import {writePretty} from './writePretty'

const connectorTemplateMeta = `
// Generated by generateConnectorStories.ts
import type {ConnectorName} from '@openint/all-connectors/name'
import type {Meta, StoryObj} from '@storybook/react'
import {defConnectors} from '@openint/all-connectors/connectors.def'
import {getConnectorModel} from '@openint/api-v1/models'
import {ConnectorCard} from '../domain-components/ConnectorCard'

function StoryWrapper(props: {name: ConnectorName}) {
  const def = defConnectors[props.name]
  if (!def) {
    throw new Error('Connector ' + props.name + ' not found')
  }
  const connector = getConnectorModel(def, {
    includeSchemas: true,
  })

  return <ConnectorCard connector={connector} />
}

const meta: Meta<typeof StoryWrapper> = {
  title: 'All Connectors/connector',
  component: StoryWrapper,
  parameters: {layout: 'centered'},
  tags: ['autodocs'],
}

export default meta
type Story = StoryObj<typeof meta>
`

const jsonSchemaTemplateMeta = `
// Generated by generateConnectorStories.ts
import type {Meta, StoryObj} from '@storybook/react'
import type {ConnectorName} from '@openint/all-connectors/name'
import {defConnectors} from '@openint/all-connectors/connectors.def'
import {Card} from '@openint/shadcn/ui'
import {zodToOas31Schema} from '@openint/util/schema'
import {JSONSchemaForm} from '../components/schema-form/JSONSchemaForm'

function FormWrapper(props: {name: ConnectorName}) {
  const schemas = defConnectors[props.name].schemas
  if (!('$key' in schemas)) {
    throw new Error(
      'Connector ' + props.name + ' does not have a $key',
    )
  }

  return (
    <Card className="w-md p-4">
      <h1 className="text-lg font-bold">{props.name} $key</h1>
      <hr />
      <JSONSchemaForm debugMode jsonSchema={zodToOas31Schema(schemas.$key)} />
    </Card>
  )
}

const meta: Meta<typeof FormWrapper> = {
  title: 'All Connectors/$key',
  component: FormWrapper,
  parameters: {layout: 'centered'},
}

export default meta
type Story = StoryObj<typeof meta>
`

async function main() {
  const connectorConfigStories = Object.entries(defConnectors)
    .filter(([_, def]) => 'connector_config' in def.schemas)
    .map(
      ([name]) => `
    export const ${camelCase(name)}ConnectorConfig: Story = {
      args: {name: '${name}'},
    }
  `,
    )

  const connectionSettingsStories = Object.entries(defConnectors)
    .filter(([_, def]) => 'connection_settings' in def.schemas)
    .map(
      ([name]) => `
    export const ${camelCase(name)}ConnectionSettings: Story = {
      args: {name: '${name}'},
    }
  `,
    )

  const connectorStories = Object.entries(defConnectors).map(
    ([name]) => `
    export const ${camelCase(name)}ConnectorCard: Story = {
      args: {name: '${name}'},
    }
  `,
  )

  const outputPath = path.join(__dirname, '../../../packages/ui-v1/__stories__')

  await writePretty(
    'ConnectorConfigForm.stories.tsx',
    jsonSchemaTemplateMeta.replaceAll('$key', 'connector_config') +
      '\n' +
      connectorConfigStories.join('\n'),
    outputPath,
  )

  await writePretty(
    'ConnectionSettingsForm.stories.tsx',
    jsonSchemaTemplateMeta.replaceAll('$key', 'connection_settings') +
      '\n' +
      connectionSettingsStories.join('\n'),
    outputPath,
  )

  await writePretty(
    'ConnectorCard.stories.tsx',
    connectorTemplateMeta + '\n' + connectorStories.join('\n'),
    outputPath,
  )
}

main()
