// generated by _generateConnectorLists.ts. Do not modify by hand
import {
  connectorAircall_server as connectorAircall,
  connectorConfluence_server as connectorConfluence,
  connectorDiscord_server as connectorDiscord,
  connectorGithub_server as connectorGithub,
  connectorGooglecalendar_server as connectorGooglecalendar,
  connectorGoogledocs_server as connectorGoogledocs,
  connectorGoogledrive_server as connectorGoogledrive,
  connectorGooglemail_server as connectorGooglemail,
  connectorGooglesheet_server as connectorGooglesheet,
  connectorHubspot_server as connectorHubspot,
  connectorLinear_server as connectorLinear,
  connectorLinkedin_server as connectorLinkedin,
  connectorNotion_server as connectorNotion,
  connectorQuickbooks_server as connectorQuickbooks,
  connectorSalesforce_server as connectorSalesforce,
  connectorSharepointonline_server as connectorSharepointonline,
  connectorSlack_server as connectorSlack,
} from '@openint/cnext'
import {default as connectorAirtable} from '@openint/connector-airtable/server'
import {default as connectorApollo} from '@openint/connector-apollo/server'
import {default as connectorBrex} from '@openint/connector-brex/server'
import {default as connectorCoda} from '@openint/connector-coda/server'
import {default as connectorFacebook} from '@openint/connector-facebook/server'
import {default as connectorFinch} from '@openint/connector-finch/server'
import {default as connectorFirebase} from '@openint/connector-firebase/server'
import {default as connectorForeceipt} from '@openint/connector-foreceipt/server'
import {default as connectorGong} from '@openint/connector-gong/server'
import {default as connectorGreenhouse} from '@openint/connector-greenhouse/server'
import {default as connectorHeron} from '@openint/connector-heron/server'
import {default as connectorInstagram} from '@openint/connector-instagram/server'
import {default as connectorIntercom} from '@openint/connector-intercom/server'
import {default as connectorJira} from '@openint/connector-jira/server'
import {default as connectorKustomer} from '@openint/connector-kustomer/server'
import {default as connectorLever} from '@openint/connector-lever/server'
import {default as connectorLunchmoney} from '@openint/connector-lunchmoney/server'
import {default as connectorMerge} from '@openint/connector-merge/server'
import {default as connectorMicrosoft} from '@openint/connector-microsoft/server'
import {default as connectorMoota} from '@openint/connector-moota/server'
import {default as connectorOnebrick} from '@openint/connector-onebrick/server'
import {default as connectorOutreach} from '@openint/connector-outreach/server'
import {default as connectorPipedrive} from '@openint/connector-pipedrive/server'
import {default as connectorPlaid} from '@openint/connector-plaid/server'
import {default as connectorPostgres} from '@openint/connector-postgres/server'
import {default as connectorRamp} from '@openint/connector-ramp/server'
import {default as connectorReddit} from '@openint/connector-reddit/server'
import {default as connectorSalesloft} from '@openint/connector-salesloft/server'
import {default as connectorSaltedge} from '@openint/connector-saltedge/server'
import {default as connectorSplitwise} from '@openint/connector-splitwise/server'
import {default as connectorStripe} from '@openint/connector-stripe/server'
import {default as connectorTeller} from '@openint/connector-teller/server'
import {default as connectorToggl} from '@openint/connector-toggl/server'
import {default as connectorTwenty} from '@openint/connector-twenty/server'
import {default as connectorTwitter} from '@openint/connector-twitter/server'
import {default as connectorWise} from '@openint/connector-wise/server'
import {default as connectorXero} from '@openint/connector-xero/server'
import {default as connectorYodlee} from '@openint/connector-yodlee/server'
import {default as connectorZohodesk} from '@openint/connector-zohodesk/server'

export const serverConnectors = {
  aircall: connectorAircall,
  airtable: connectorAirtable,
  apollo: connectorApollo,
  brex: connectorBrex,
  coda: connectorCoda,
  confluence: connectorConfluence,
  discord: connectorDiscord,
  facebook: connectorFacebook,
  finch: connectorFinch,
  firebase: connectorFirebase,
  foreceipt: connectorForeceipt,
  github: connectorGithub,
  gong: connectorGong,
  googlecalendar: connectorGooglecalendar,
  googledocs: connectorGoogledocs,
  googledrive: connectorGoogledrive,
  googlemail: connectorGooglemail,
  googlesheet: connectorGooglesheet,
  greenhouse: connectorGreenhouse,
  heron: connectorHeron,
  hubspot: connectorHubspot,
  instagram: connectorInstagram,
  intercom: connectorIntercom,
  jira: connectorJira,
  kustomer: connectorKustomer,
  lever: connectorLever,
  linear: connectorLinear,
  linkedin: connectorLinkedin,
  lunchmoney: connectorLunchmoney,
  merge: connectorMerge,
  microsoft: connectorMicrosoft,
  moota: connectorMoota,
  notion: connectorNotion,
  onebrick: connectorOnebrick,
  outreach: connectorOutreach,
  pipedrive: connectorPipedrive,
  plaid: connectorPlaid,
  postgres: connectorPostgres,
  quickbooks: connectorQuickbooks,
  ramp: connectorRamp,
  reddit: connectorReddit,
  salesforce: connectorSalesforce,
  salesloft: connectorSalesloft,
  saltedge: connectorSaltedge,
  sharepointonline: connectorSharepointonline,
  slack: connectorSlack,
  splitwise: connectorSplitwise,
  stripe: connectorStripe,
  teller: connectorTeller,
  toggl: connectorToggl,
  twenty: connectorTwenty,
  twitter: connectorTwitter,
  wise: connectorWise,
  xero: connectorXero,
  yodlee: connectorYodlee,
  zohodesk: connectorZohodesk,
}
