// generated by _generateConnectorLists.ts. Do not modify by hand
import {
  connectorGoogledrive_def,
  connectorGoogledrive_server,
  connectorGooglesheet_def,
  connectorGooglesheet_server,
} from '@openint/cnext'
import {default as connectorAircall_def} from '@openint/connector-aircall/def'
import {default as connectorAircall_server} from '@openint/connector-aircall/server'
import {default as connectorAirtable_def} from '@openint/connector-airtable/def'
import {default as connectorAirtable_server} from '@openint/connector-airtable/server'
import {default as connectorApollo_def} from '@openint/connector-apollo/def'
import {default as connectorApollo_server} from '@openint/connector-apollo/server'
import {default as connectorBrex_def} from '@openint/connector-brex/def'
import {default as connectorBrex_server} from '@openint/connector-brex/server'
import {default as connectorCoda_def} from '@openint/connector-coda/def'
import {default as connectorCoda_server} from '@openint/connector-coda/server'
import {default as connectorConfluence_def} from '@openint/connector-confluence/def'
import {default as connectorConfluence_server} from '@openint/connector-confluence/server'
import {default as connectorDiscord_def} from '@openint/connector-discord/def'
import {default as connectorDiscord_server} from '@openint/connector-discord/server'
import {default as connectorFacebook_def} from '@openint/connector-facebook/def'
import {default as connectorFacebook_server} from '@openint/connector-facebook/server'
import {default as connectorFinch_def} from '@openint/connector-finch/def'
import {default as connectorFinch_server} from '@openint/connector-finch/server'
import {default as connectorFirebase_def} from '@openint/connector-firebase/def'
import {default as connectorFirebase_server} from '@openint/connector-firebase/server'
import {default as connectorForeceipt_def} from '@openint/connector-foreceipt/def'
import {default as connectorForeceipt_server} from '@openint/connector-foreceipt/server'
import {default as connectorGithub_def} from '@openint/connector-github/def'
import {default as connectorGithub_server} from '@openint/connector-github/server'
import {default as connectorGong_def} from '@openint/connector-gong/def'
import {default as connectorGong_server} from '@openint/connector-gong/server'
import {default as connectorGoogle_def} from '@openint/connector-google/def'
import {default as connectorGoogle_server} from '@openint/connector-google/server'
import {default as connectorGreenhouse_def} from '@openint/connector-greenhouse/def'
import {default as connectorGreenhouse_server} from '@openint/connector-greenhouse/server'
import {default as connectorHeron_def} from '@openint/connector-heron/def'
import {default as connectorHeron_server} from '@openint/connector-heron/server'
import {default as connectorHubspot_def} from '@openint/connector-hubspot/def'
import {default as connectorHubspot_server} from '@openint/connector-hubspot/server'
import {default as connectorInstagram_def} from '@openint/connector-instagram/def'
import {default as connectorInstagram_server} from '@openint/connector-instagram/server'
import {default as connectorIntercom_def} from '@openint/connector-intercom/def'
import {default as connectorIntercom_server} from '@openint/connector-intercom/server'
import {default as connectorJira_def} from '@openint/connector-jira/def'
import {default as connectorJira_server} from '@openint/connector-jira/server'
import {default as connectorKustomer_def} from '@openint/connector-kustomer/def'
import {default as connectorKustomer_server} from '@openint/connector-kustomer/server'
import {default as connectorLever_def} from '@openint/connector-lever/def'
import {default as connectorLever_server} from '@openint/connector-lever/server'
import {default as connectorLinear_def} from '@openint/connector-linear/def'
import {default as connectorLinear_server} from '@openint/connector-linear/server'
import {default as connectorLinkedin_def} from '@openint/connector-linkedin/def'
import {default as connectorLinkedin_server} from '@openint/connector-linkedin/server'
import {default as connectorLunchmoney_def} from '@openint/connector-lunchmoney/def'
import {default as connectorLunchmoney_server} from '@openint/connector-lunchmoney/server'
import {default as connectorMercury_def} from '@openint/connector-mercury/def'
import {default as connectorMerge_def} from '@openint/connector-merge/def'
import {default as connectorMerge_server} from '@openint/connector-merge/server'
import {default as connectorMicrosoft_def} from '@openint/connector-microsoft/def'
import {default as connectorMicrosoft_server} from '@openint/connector-microsoft/server'
import {default as connectorMoota_def} from '@openint/connector-moota/def'
import {default as connectorMoota_server} from '@openint/connector-moota/server'
import {default as connectorNotion_def} from '@openint/connector-notion/def'
import {default as connectorNotion_server} from '@openint/connector-notion/server'
import {default as connectorOnebrick_def} from '@openint/connector-onebrick/def'
import {default as connectorOnebrick_server} from '@openint/connector-onebrick/server'
import {default as connectorOutreach_def} from '@openint/connector-outreach/def'
import {default as connectorOutreach_server} from '@openint/connector-outreach/server'
import {default as connectorPipedrive_def} from '@openint/connector-pipedrive/def'
import {default as connectorPipedrive_server} from '@openint/connector-pipedrive/server'
import {default as connectorPlaid_def} from '@openint/connector-plaid/def'
import {default as connectorPlaid_server} from '@openint/connector-plaid/server'
import {default as connectorPostgres_def} from '@openint/connector-postgres/def'
import {default as connectorPostgres_server} from '@openint/connector-postgres/server'
import {default as connectorQbo_def} from '@openint/connector-qbo/def'
import {default as connectorQbo_server} from '@openint/connector-qbo/server'
import {default as connectorRamp_def} from '@openint/connector-ramp/def'
import {default as connectorRamp_server} from '@openint/connector-ramp/server'
import {default as connectorReddit_def} from '@openint/connector-reddit/def'
import {default as connectorReddit_server} from '@openint/connector-reddit/server'
import {default as connectorSalesforce_def} from '@openint/connector-salesforce/def'
import {default as connectorSalesforce_server} from '@openint/connector-salesforce/server'
import {default as connectorSalesloft_def} from '@openint/connector-salesloft/def'
import {default as connectorSalesloft_server} from '@openint/connector-salesloft/server'
import {default as connectorSaltedge_def} from '@openint/connector-saltedge/def'
import {default as connectorSaltedge_server} from '@openint/connector-saltedge/server'
import {default as connectorSlack_def} from '@openint/connector-slack/def'
import {default as connectorSlack_server} from '@openint/connector-slack/server'
import {default as connectorSplitwise_def} from '@openint/connector-splitwise/def'
import {default as connectorSplitwise_server} from '@openint/connector-splitwise/server'
import {default as connectorStripe_def} from '@openint/connector-stripe/def'
import {default as connectorStripe_server} from '@openint/connector-stripe/server'
import {default as connectorTeller_def} from '@openint/connector-teller/def'
import {default as connectorTeller_server} from '@openint/connector-teller/server'
import {default as connectorToggl_def} from '@openint/connector-toggl/def'
import {default as connectorToggl_server} from '@openint/connector-toggl/server'
import {default as connectorTwenty_def} from '@openint/connector-twenty/def'
import {default as connectorTwenty_server} from '@openint/connector-twenty/server'
import {default as connectorTwitter_def} from '@openint/connector-twitter/def'
import {default as connectorTwitter_server} from '@openint/connector-twitter/server'
import {default as connectorVenmo_def} from '@openint/connector-venmo/def'
import {default as connectorWise_def} from '@openint/connector-wise/def'
import {default as connectorWise_server} from '@openint/connector-wise/server'
import {default as connectorXero_def} from '@openint/connector-xero/def'
import {default as connectorXero_server} from '@openint/connector-xero/server'
import {default as connectorYodlee_def} from '@openint/connector-yodlee/def'
import {default as connectorYodlee_server} from '@openint/connector-yodlee/server'
import {default as connectorZohodesk_def} from '@openint/connector-zohodesk/def'
import {default as connectorZohodesk_server} from '@openint/connector-zohodesk/server'

const connectorAircall = {
  ...connectorAircall_def,
  ...connectorAircall_server,
}

const connectorAirtable = {
  ...connectorAirtable_def,
  ...connectorAirtable_server,
}

const connectorApollo = {
  ...connectorApollo_def,
  ...connectorApollo_server,
}

const connectorBrex = {
  ...connectorBrex_def,
  ...connectorBrex_server,
}

const connectorCoda = {
  ...connectorCoda_def,
  ...connectorCoda_server,
}

const connectorConfluence = {
  ...connectorConfluence_def,
  ...connectorConfluence_server,
}

const connectorDiscord = {
  ...connectorDiscord_def,
  ...connectorDiscord_server,
}

const connectorFacebook = {
  ...connectorFacebook_def,
  ...connectorFacebook_server,
}

const connectorFinch = {
  ...connectorFinch_def,
  ...connectorFinch_server,
}

const connectorFirebase = {
  ...connectorFirebase_def,
  ...connectorFirebase_server,
}

const connectorForeceipt = {
  ...connectorForeceipt_def,
  ...connectorForeceipt_server,
}

const connectorGithub = {
  ...connectorGithub_def,
  ...connectorGithub_server,
}

const connectorGong = {
  ...connectorGong_def,
  ...connectorGong_server,
}

const connectorGoogle = {
  ...connectorGoogle_def,
  ...connectorGoogle_server,
}

const connectorGreenhouse = {
  ...connectorGreenhouse_def,
  ...connectorGreenhouse_server,
}

const connectorHeron = {
  ...connectorHeron_def,
  ...connectorHeron_server,
}

const connectorHubspot = {
  ...connectorHubspot_def,
  ...connectorHubspot_server,
}

const connectorInstagram = {
  ...connectorInstagram_def,
  ...connectorInstagram_server,
}

const connectorIntercom = {
  ...connectorIntercom_def,
  ...connectorIntercom_server,
}

const connectorJira = {
  ...connectorJira_def,
  ...connectorJira_server,
}

const connectorKustomer = {
  ...connectorKustomer_def,
  ...connectorKustomer_server,
}

const connectorLever = {
  ...connectorLever_def,
  ...connectorLever_server,
}

const connectorLinear = {
  ...connectorLinear_def,
  ...connectorLinear_server,
}

const connectorLinkedin = {
  ...connectorLinkedin_def,
  ...connectorLinkedin_server,
}

const connectorLunchmoney = {
  ...connectorLunchmoney_def,
  ...connectorLunchmoney_server,
}

const connectorMercury = {
  ...connectorMercury_def,
}

const connectorMerge = {
  ...connectorMerge_def,
  ...connectorMerge_server,
}

const connectorMicrosoft = {
  ...connectorMicrosoft_def,
  ...connectorMicrosoft_server,
}

const connectorMoota = {
  ...connectorMoota_def,
  ...connectorMoota_server,
}

const connectorNotion = {
  ...connectorNotion_def,
  ...connectorNotion_server,
}

const connectorOnebrick = {
  ...connectorOnebrick_def,
  ...connectorOnebrick_server,
}

const connectorOutreach = {
  ...connectorOutreach_def,
  ...connectorOutreach_server,
}

const connectorPipedrive = {
  ...connectorPipedrive_def,
  ...connectorPipedrive_server,
}

const connectorPlaid = {
  ...connectorPlaid_def,
  ...connectorPlaid_server,
}

const connectorPostgres = {
  ...connectorPostgres_def,
  ...connectorPostgres_server,
}

const connectorQbo = {
  ...connectorQbo_def,
  ...connectorQbo_server,
}

const connectorRamp = {
  ...connectorRamp_def,
  ...connectorRamp_server,
}

const connectorReddit = {
  ...connectorReddit_def,
  ...connectorReddit_server,
}

const connectorSalesforce = {
  ...connectorSalesforce_def,
  ...connectorSalesforce_server,
}

const connectorSalesloft = {
  ...connectorSalesloft_def,
  ...connectorSalesloft_server,
}

const connectorSaltedge = {
  ...connectorSaltedge_def,
  ...connectorSaltedge_server,
}

const connectorSlack = {
  ...connectorSlack_def,
  ...connectorSlack_server,
}

const connectorSplitwise = {
  ...connectorSplitwise_def,
  ...connectorSplitwise_server,
}

const connectorStripe = {
  ...connectorStripe_def,
  ...connectorStripe_server,
}

const connectorTeller = {
  ...connectorTeller_def,
  ...connectorTeller_server,
}

const connectorToggl = {
  ...connectorToggl_def,
  ...connectorToggl_server,
}

const connectorTwenty = {
  ...connectorTwenty_def,
  ...connectorTwenty_server,
}

const connectorTwitter = {
  ...connectorTwitter_def,
  ...connectorTwitter_server,
}

const connectorVenmo = {
  ...connectorVenmo_def,
}

const connectorWise = {
  ...connectorWise_def,
  ...connectorWise_server,
}

const connectorXero = {
  ...connectorXero_def,
  ...connectorXero_server,
}

const connectorYodlee = {
  ...connectorYodlee_def,
  ...connectorYodlee_server,
}

const connectorZohodesk = {
  ...connectorZohodesk_def,
  ...connectorZohodesk_server,
}

const connectorGoogledrive = {
  ...connectorGoogledrive_def,
  ...connectorGoogledrive_server,
}

const connectorGooglesheet = {
  ...connectorGooglesheet_def,
  ...connectorGooglesheet_server,
}

export const mergedConnectors = {
  aircall: connectorAircall,
  airtable: connectorAirtable,
  apollo: connectorApollo,
  brex: connectorBrex,
  coda: connectorCoda,
  confluence: connectorConfluence,
  discord: connectorDiscord,
  facebook: connectorFacebook,
  finch: connectorFinch,
  firebase: connectorFirebase,
  foreceipt: connectorForeceipt,
  github: connectorGithub,
  gong: connectorGong,
  google: connectorGoogle,
  greenhouse: connectorGreenhouse,
  heron: connectorHeron,
  hubspot: connectorHubspot,
  instagram: connectorInstagram,
  intercom: connectorIntercom,
  jira: connectorJira,
  kustomer: connectorKustomer,
  lever: connectorLever,
  linear: connectorLinear,
  linkedin: connectorLinkedin,
  lunchmoney: connectorLunchmoney,
  mercury: connectorMercury,
  merge: connectorMerge,
  microsoft: connectorMicrosoft,
  moota: connectorMoota,
  notion: connectorNotion,
  onebrick: connectorOnebrick,
  outreach: connectorOutreach,
  pipedrive: connectorPipedrive,
  plaid: connectorPlaid,
  postgres: connectorPostgres,
  qbo: connectorQbo,
  ramp: connectorRamp,
  reddit: connectorReddit,
  salesforce: connectorSalesforce,
  salesloft: connectorSalesloft,
  saltedge: connectorSaltedge,
  slack: connectorSlack,
  splitwise: connectorSplitwise,
  stripe: connectorStripe,
  teller: connectorTeller,
  toggl: connectorToggl,
  twenty: connectorTwenty,
  twitter: connectorTwitter,
  venmo: connectorVenmo,
  wise: connectorWise,
  xero: connectorXero,
  yodlee: connectorYodlee,
  zohodesk: connectorZohodesk,
  googledrive: connectorGoogledrive,
  googlesheet: connectorGooglesheet,
}
