// generated by _generateConnectorLists.ts. Do not modify by hand
export const clientConnectors = {
  finch: () => import('@openint/connector-finch/client'),
  merge: () => import('@openint/connector-merge/client'),
  onebrick: () => import('@openint/connector-onebrick/client'),
  plaid: () => import('@openint/connector-plaid/client'),
  teller: () => import('@openint/connector-teller/client'),
  yodlee: () => import('@openint/connector-yodlee/client'),
}
