// generated by _generateConnectorLists.ts. Do not modify by hand

module.exports = [
  {dirName: 'all-connectors', varName: 'allConnectors', imports: {}},
  {
    name: 'airtable',
    dirName: 'connector-airtable',
    varName: 'connectorAirtable',
    imports: {
      def: '@openint/connector-airtable/def',
      server: '@openint/connector-airtable/server',
    },
  },
  {
    name: 'apollo',
    dirName: 'connector-apollo',
    varName: 'connectorApollo',
    imports: {
      def: '@openint/connector-apollo/def',
      server: '@openint/connector-apollo/server',
    },
  },
  {dirName: 'connector-beancount', varName: 'connectorBeancount', imports: {}},
  {
    name: 'brex',
    dirName: 'connector-brex',
    varName: 'connectorBrex',
    imports: {
      def: '@openint/connector-brex/def',
      server: '@openint/connector-brex/server',
    },
  },
  {
    name: 'coda',
    dirName: 'connector-coda',
    varName: 'connectorCoda',
    imports: {
      def: '@openint/connector-coda/def',
      server: '@openint/connector-coda/server',
    },
  },
  {dirName: 'connector-expensify', varName: 'connectorExpensify', imports: {}},
  {
    name: 'facebook',
    dirName: 'connector-facebook',
    varName: 'connectorFacebook',
    imports: {
      def: '@openint/connector-facebook/def',
      server: '@openint/connector-facebook/server',
    },
  },
  {
    name: 'finch',
    dirName: 'connector-finch',
    varName: 'connectorFinch',
    imports: {
      def: '@openint/connector-finch/def',
      client: '@openint/connector-finch/client',
      server: '@openint/connector-finch/server',
    },
  },
  {
    name: 'firebase',
    dirName: 'connector-firebase',
    varName: 'connectorFirebase',
    imports: {
      def: '@openint/connector-firebase/def',
      server: '@openint/connector-firebase/server',
    },
  },
  {
    name: 'foreceipt',
    dirName: 'connector-foreceipt',
    varName: 'connectorForeceipt',
    imports: {
      def: '@openint/connector-foreceipt/def',
      server: '@openint/connector-foreceipt/server',
    },
  },
  {
    name: 'github',
    dirName: 'connector-github',
    varName: 'connectorGithub',
    imports: {
      def: '@openint/connector-github/def',
      server: '@openint/connector-github/server',
    },
  },
  {
    name: 'gong',
    dirName: 'connector-gong',
    varName: 'connectorGong',
    imports: {
      def: '@openint/connector-gong/def',
      server: '@openint/connector-gong/server',
    },
  },
  {
    name: 'greenhouse',
    dirName: 'connector-greenhouse',
    varName: 'connectorGreenhouse',
    imports: {
      def: '@openint/connector-greenhouse/def',
      server: '@openint/connector-greenhouse/server',
    },
  },
  {
    name: 'heron',
    dirName: 'connector-heron',
    varName: 'connectorHeron',
    imports: {
      def: '@openint/connector-heron/def',
      server: '@openint/connector-heron/server',
    },
  },
  {
    name: 'hubspot',
    dirName: 'connector-hubspot',
    varName: 'connectorHubspot',
    imports: {
      def: '@openint/connector-hubspot/def',
      server: '@openint/connector-hubspot/server',
    },
  },
  {
    name: 'instagram',
    dirName: 'connector-instagram',
    varName: 'connectorInstagram',
    imports: {
      def: '@openint/connector-instagram/def',
      server: '@openint/connector-instagram/server',
    },
  },
  {
    name: 'intercom',
    dirName: 'connector-intercom',
    varName: 'connectorIntercom',
    imports: {
      def: '@openint/connector-intercom/def',
      server: '@openint/connector-intercom/server',
    },
  },
  {
    name: 'jira',
    dirName: 'connector-jira',
    varName: 'connectorJira',
    imports: {
      def: '@openint/connector-jira/def',
      server: '@openint/connector-jira/server',
    },
  },
  {
    name: 'kustomer',
    dirName: 'connector-kustomer',
    varName: 'connectorKustomer',
    imports: {
      def: '@openint/connector-kustomer/def',
      server: '@openint/connector-kustomer/server',
    },
  },
  {
    name: 'lever',
    dirName: 'connector-lever',
    varName: 'connectorLever',
    imports: {
      def: '@openint/connector-lever/def',
      server: '@openint/connector-lever/server',
    },
  },
  {
    name: 'linear',
    dirName: 'connector-linear',
    varName: 'connectorLinear',
    imports: {
      def: '@openint/connector-linear/def',
      server: '@openint/connector-linear/server',
    },
  },
  {
    name: 'linkedin',
    dirName: 'connector-linkedin',
    varName: 'connectorLinkedin',
    imports: {
      def: '@openint/connector-linkedin/def',
      server: '@openint/connector-linkedin/server',
    },
  },
  {
    name: 'lunchmoney',
    dirName: 'connector-lunchmoney',
    varName: 'connectorLunchmoney',
    imports: {
      def: '@openint/connector-lunchmoney/def',
      server: '@openint/connector-lunchmoney/server',
    },
  },
  {
    name: 'mercury',
    dirName: 'connector-mercury',
    varName: 'connectorMercury',
    imports: {def: '@openint/connector-mercury/def'},
  },
  {
    name: 'merge',
    dirName: 'connector-merge',
    varName: 'connectorMerge',
    imports: {
      def: '@openint/connector-merge/def',
      client: '@openint/connector-merge/client',
      server: '@openint/connector-merge/server',
    },
  },
  {
    name: 'microsoft',
    dirName: 'connector-microsoft',
    varName: 'connectorMicrosoft',
    imports: {
      def: '@openint/connector-microsoft/def',
      server: '@openint/connector-microsoft/server',
    },
  },
  {
    name: 'moota',
    dirName: 'connector-moota',
    varName: 'connectorMoota',
    imports: {
      def: '@openint/connector-moota/def',
      server: '@openint/connector-moota/server',
    },
  },
  {
    name: 'notion',
    dirName: 'connector-notion',
    varName: 'connectorNotion',
    imports: {
      def: '@openint/connector-notion/def',
      server: '@openint/connector-notion/server',
    },
  },
  {
    name: 'onebrick',
    dirName: 'connector-onebrick',
    varName: 'connectorOnebrick',
    imports: {
      def: '@openint/connector-onebrick/def',
      client: '@openint/connector-onebrick/client',
      server: '@openint/connector-onebrick/server',
    },
  },
  {
    name: 'outreach',
    dirName: 'connector-outreach',
    varName: 'connectorOutreach',
    imports: {
      def: '@openint/connector-outreach/def',
      server: '@openint/connector-outreach/server',
    },
  },
  {
    name: 'pipedrive',
    dirName: 'connector-pipedrive',
    varName: 'connectorPipedrive',
    imports: {
      def: '@openint/connector-pipedrive/def',
      server: '@openint/connector-pipedrive/server',
    },
  },
  {
    name: 'plaid',
    dirName: 'connector-plaid',
    varName: 'connectorPlaid',
    imports: {
      def: '@openint/connector-plaid/def',
      client: '@openint/connector-plaid/client',
      server: '@openint/connector-plaid/server',
    },
  },
  {
    name: 'postgres',
    dirName: 'connector-postgres',
    varName: 'connectorPostgres',
    imports: {
      def: '@openint/connector-postgres/def',
      server: '@openint/connector-postgres/server',
    },
  },
  {
    name: 'qbo',
    dirName: 'connector-qbo',
    varName: 'connectorQbo',
    imports: {
      def: '@openint/connector-qbo/def',
      server: '@openint/connector-qbo/server',
    },
  },
  {
    name: 'ramp',
    dirName: 'connector-ramp',
    varName: 'connectorRamp',
    imports: {
      def: '@openint/connector-ramp/def',
      server: '@openint/connector-ramp/server',
    },
  },
  {
    name: 'reddit',
    dirName: 'connector-reddit',
    varName: 'connectorReddit',
    imports: {
      def: '@openint/connector-reddit/def',
      server: '@openint/connector-reddit/server',
    },
  },
  {
    name: 'salesforce',
    dirName: 'connector-salesforce',
    varName: 'connectorSalesforce',
    imports: {
      def: '@openint/connector-salesforce/def',
      server: '@openint/connector-salesforce/server',
    },
  },
  {
    name: 'salesloft',
    dirName: 'connector-salesloft',
    varName: 'connectorSalesloft',
    imports: {
      def: '@openint/connector-salesloft/def',
      server: '@openint/connector-salesloft/server',
    },
  },
  {
    name: 'saltedge',
    dirName: 'connector-saltedge',
    varName: 'connectorSaltedge',
    imports: {
      def: '@openint/connector-saltedge/def',
      server: '@openint/connector-saltedge/server',
    },
  },
  {
    name: 'slack',
    dirName: 'connector-slack',
    varName: 'connectorSlack',
    imports: {
      def: '@openint/connector-slack/def',
      server: '@openint/connector-slack/server',
    },
  },
  {
    name: 'splitwise',
    dirName: 'connector-splitwise',
    varName: 'connectorSplitwise',
    imports: {
      def: '@openint/connector-splitwise/def',
      server: '@openint/connector-splitwise/server',
    },
  },
  {
    name: 'stripe',
    dirName: 'connector-stripe',
    varName: 'connectorStripe',
    imports: {
      def: '@openint/connector-stripe/def',
      server: '@openint/connector-stripe/server',
    },
  },
  {
    name: 'teller',
    dirName: 'connector-teller',
    varName: 'connectorTeller',
    imports: {
      def: '@openint/connector-teller/def',
      client: '@openint/connector-teller/client',
      server: '@openint/connector-teller/server',
    },
  },
  {
    name: 'toggl',
    dirName: 'connector-toggl',
    varName: 'connectorToggl',
    imports: {
      def: '@openint/connector-toggl/def',
      server: '@openint/connector-toggl/server',
    },
  },
  {
    name: 'twenty',
    dirName: 'connector-twenty',
    varName: 'connectorTwenty',
    imports: {
      def: '@openint/connector-twenty/def',
      server: '@openint/connector-twenty/server',
    },
  },
  {
    name: 'twitter',
    dirName: 'connector-twitter',
    varName: 'connectorTwitter',
    imports: {
      def: '@openint/connector-twitter/def',
      server: '@openint/connector-twitter/server',
    },
  },
  {
    name: 'venmo',
    dirName: 'connector-venmo',
    varName: 'connectorVenmo',
    imports: {def: '@openint/connector-venmo/def'},
  },
  {
    name: 'wise',
    dirName: 'connector-wise',
    varName: 'connectorWise',
    imports: {
      def: '@openint/connector-wise/def',
      server: '@openint/connector-wise/server',
    },
  },
  {
    name: 'xero',
    dirName: 'connector-xero',
    varName: 'connectorXero',
    imports: {
      def: '@openint/connector-xero/def',
      server: '@openint/connector-xero/server',
    },
  },
  {
    name: 'yodlee',
    dirName: 'connector-yodlee',
    varName: 'connectorYodlee',
    imports: {
      def: '@openint/connector-yodlee/def',
      client: '@openint/connector-yodlee/client',
      server: '@openint/connector-yodlee/server',
    },
  },
  {
    name: 'zohodesk',
    dirName: 'connector-zohodesk',
    varName: 'connectorZohodesk',
    imports: {
      def: '@openint/connector-zohodesk/def',
      server: '@openint/connector-zohodesk/server',
    },
  },
  {
    name: 'aircall',
    dirName: 'cnext-aircall',
    varName: 'connectorAircall',
    imports: {
      def: '@openint/cnext',
      server: '@openint/cnext',
      importPath: {
        def: 'connectorAircall_def',
        server: 'connectorAircall_server',
      },
    },
  },
  {
    name: 'confluence',
    dirName: 'cnext-confluence',
    varName: 'connectorConfluence',
    imports: {
      def: '@openint/cnext',
      server: '@openint/cnext',
      importPath: {
        def: 'connectorConfluence_def',
        server: 'connectorConfluence_server',
      },
    },
  },
  {
    name: 'discord',
    dirName: 'cnext-discord',
    varName: 'connectorDiscord',
    imports: {
      def: '@openint/cnext',
      server: '@openint/cnext',
      importPath: {
        def: 'connectorDiscord_def',
        server: 'connectorDiscord_server',
      },
    },
  },
  {
    name: 'googlecalendar',
    dirName: 'cnext-googlecalendar',
    varName: 'connectorGooglecalendar',
    imports: {
      def: '@openint/cnext',
      server: '@openint/cnext',
      importPath: {
        def: 'connectorGooglecalendar_def',
        server: 'connectorGooglecalendar_server',
      },
    },
  },
  {
    name: 'googledocs',
    dirName: 'cnext-googledocs',
    varName: 'connectorGoogledocs',
    imports: {
      def: '@openint/cnext',
      server: '@openint/cnext',
      importPath: {
        def: 'connectorGoogledocs_def',
        server: 'connectorGoogledocs_server',
      },
    },
  },
  {
    name: 'googledrive',
    dirName: 'cnext-googledrive',
    varName: 'connectorGoogledrive',
    imports: {
      def: '@openint/cnext',
      server: '@openint/cnext',
      importPath: {
        def: 'connectorGoogledrive_def',
        server: 'connectorGoogledrive_server',
      },
    },
  },
  {
    name: 'googlemail',
    dirName: 'cnext-googlemail',
    varName: 'connectorGooglemail',
    imports: {
      def: '@openint/cnext',
      server: '@openint/cnext',
      importPath: {
        def: 'connectorGooglemail_def',
        server: 'connectorGooglemail_server',
      },
    },
  },
  {
    name: 'googlesheet',
    dirName: 'cnext-googlesheet',
    varName: 'connectorGooglesheet',
    imports: {
      def: '@openint/cnext',
      server: '@openint/cnext',
      importPath: {
        def: 'connectorGooglesheet_def',
        server: 'connectorGooglesheet_server',
      },
    },
  },
]
