name: Manual Docs Release

on:
  workflow_dispatch:

jobs:
  upload-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push spec and config to Stainless
        uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: '/packages-v1/api-v1/__generated__/openapi.json'
          output_path: '/packages-v1/api-v1/__generated__/openapi.documented.json'
          project_name: 'openint'
          commit_message: 'feat(docs): updating documented docs for mintlify'
