name: Stably Test Runner

on:
  workflow_dispatch:
  push:
    branches:
      - production

permissions:
  pull-requests: write
  contents: write

jobs:
  stably-test-action:
    name: Stably Test Runner
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 5 minutes for any remaining Vercel Main Branch Deployment
        run: sleep 300
      - name: Stably Runner Action
        id: stably-runner
        uses: stablyhq/stably-runner-action@v3
        with:
          api-key: ${{ secrets.STABLY_API_KEY }}
          test-group-id: cm5g8i6nc0005l103urkixuxz
